add flag to app to switch on/off output of npm-debug.log

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -12,8 +12,10 @@ bp_dir=$(cd $(dirname $0); cd ..; pwd)
 # Load some convenience functions like status(), echo(), and indent()
 source $bp_dir/bin/common.sh
 
-# Output npm debug info on error
-trap cat_npm_debug_log ERR
+if [ -f /app/.npm_debug_log ]; then
+  # Output npm debug info on error
+  trap cat_npm_debug_log ERR
+fi
 
 # Look in package.json's engines.node field for a semver range
 semver_range=$(cat $build_dir/package.json | $bp_dir/vendor/jq -r .engines.node)
